import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:firebase_auth/firebase_auth.dart';
import './subscription_service.dart';

// Part file for Riverpod code generation (will be generated by build_runner)
part 'pro_action_verification_service.g.dart';

@Riverpod(keepAlive: true)
ProActionVerificationService proActionVerificationService(ProActionVerificationServiceRef ref) {
  final subscriptionService = ref.watch(subscriptionServiceProvider);
  return ProActionVerificationService(subscriptionService: subscriptionService);
}

class ProActionVerificationService {
  final SubscriptionService subscriptionService;

  ProActionVerificationService({required this.subscriptionService});

  /// Verifies if the current user has premium access for a specific action.
  /// Throws a [ProAccessDeniedException] if not.
  Future<void> verifyProAccess(String actionType) async {
    final bool isPro = await subscriptionService.isProSubscriber();
    if (!isPro) {
      throw ProAccessDeniedException('Premium access required for $actionType.');
    }
  }
}

class ProAccessDeniedException implements Exception {
  final String message;
  ProAccessDeniedException(this.message);

  @override
  String toString() => 'ProAccessDeniedException: $message';
}
