// Mocks generated by Mockito 5.4.6 from annotations
// in journeyman_jobs/test/features/crews/services/crew_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i11;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:journeyman_jobs/core/services/connectivity_service.dart' as _i9;
import 'package:journeyman_jobs/core/services/offline_data_service.dart' as _i6;
import 'package:journeyman_jobs/features/crews/crews.dart' as _i5;
import 'package:journeyman_jobs/features/crews/services/job_matching_service_impl.dart'
    as _i12;
import 'package:journeyman_jobs/features/crews/services/job_sharing_service_impl.dart'
    as _i2;
import 'package:journeyman_jobs/features/jobs/jobs.dart' as _i7;
import 'package:journeyman_jobs/features/unions/unions.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JobSharingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobSharingService extends _i1.Mock implements _i2.JobSharingService {
  @override
  _i3.Future<void> shareToCrews({
    required _i4.DocumentReference<Object?>? jobReference,
    required List<String>? crewIds,
    required String? sharedBy,
    required String? crewNotes,
    required Map<String, dynamic>? jobSnapshot,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareToCrews,
          [],
          {
            #jobReference: jobReference,
            #crewIds: crewIds,
            #sharedBy: sharedBy,
            #crewNotes: crewNotes,
            #jobSnapshot: jobSnapshot,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i5.SharedJob>> getSharedJobsStream(String? crewId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSharedJobsStream,
          [crewId],
        ),
        returnValue: _i3.Stream<List<_i5.SharedJob>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i5.SharedJob>>.empty(),
      ) as _i3.Stream<List<_i5.SharedJob>>);

  @override
  _i3.Future<Map<String, dynamic>> getCrewSharingAnalytics(String? crewId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCrewSharingAnalytics,
          [crewId],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [OfflineDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineDataService extends _i1.Mock
    implements _i6.OfflineDataService {
  @override
  _i3.Stream<bool> get syncStatusStream => (super.noSuchMethod(
        Invocation.getter(#syncStatusStream),
        returnValue: _i3.Stream<bool>.empty(),
        returnValueForMissingStub: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Stream<Map<String, dynamic>> get dataUpdateStream => (super.noSuchMethod(
        Invocation.getter(#dataUpdateStream),
        returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
        returnValueForMissingStub: _i3.Stream<Map<String, dynamic>>.empty(),
      ) as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<double> get syncProgressStream => (super.noSuchMethod(
        Invocation.getter(#syncProgressStream),
        returnValue: _i3.Stream<double>.empty(),
        returnValueForMissingStub: _i3.Stream<double>.empty(),
      ) as _i3.Stream<double>);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get pendingChangesCount => (super.noSuchMethod(
        Invocation.getter(#pendingChangesCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i6.SyncStrategy get syncStrategy => (super.noSuchMethod(
        Invocation.getter(#syncStrategy),
        returnValue: _i6.SyncStrategy.immediate,
        returnValueForMissingStub: _i6.SyncStrategy.immediate,
      ) as _i6.SyncStrategy);

  @override
  bool get isOfflineDataAvailable => (super.noSuchMethod(
        Invocation.getter(#isOfflineDataAvailable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> storeJobsOffline(
    List<_i7.Job>? jobs, {
    _i6.SyncPriority? priority = _i6.SyncPriority.medium,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeJobsOffline,
          [jobs],
          {#priority: priority},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Job>> getOfflineJobs({bool? includeExpired = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineJobs,
          [],
          {#includeExpired: includeExpired},
        ),
        returnValue: _i3.Future<List<_i7.Job>>.value(<_i7.Job>[]),
        returnValueForMissingStub: _i3.Future<List<_i7.Job>>.value(<_i7.Job>[]),
      ) as _i3.Future<List<_i7.Job>>);

  @override
  _i3.Future<void> storeLocalsOffline(
    List<_i8.LocalsRecord>? locals, {
    _i6.SyncPriority? priority = _i6.SyncPriority.low,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeLocalsOffline,
          [locals],
          {#priority: priority},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.LocalsRecord>> getOfflineLocals(
          {bool? includeExpired = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineLocals,
          [],
          {#includeExpired: includeExpired},
        ),
        returnValue:
            _i3.Future<List<_i8.LocalsRecord>>.value(<_i8.LocalsRecord>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i8.LocalsRecord>>.value(<_i8.LocalsRecord>[]),
      ) as _i3.Future<List<_i8.LocalsRecord>>);

  @override
  _i3.Future<void> storeUserPreferencesOffline(
          Map<String, dynamic>? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeUserPreferencesOffline,
          [preferences],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getOfflineUserPreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineUserPreferences,
          [],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> storeSearchHistoryOffline(
          List<Map<String, dynamic>>? searchHistory) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSearchHistoryOffline,
          [searchHistory],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getOfflineSearchHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineSearchHistory,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> storeBookmarksOffline(List<String>? jobIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeBookmarksOffline,
          [jobIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getOfflineBookmarks() => (super.noSuchMethod(
        Invocation.method(
          #getOfflineBookmarks,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> storeCrewsOffline(
    List<_i5.Crew>? crews, {
    _i6.SyncPriority? priority = _i6.SyncPriority.medium,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeCrewsOffline,
          [crews],
          {#priority: priority},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Crew>> getOfflineCrews({bool? includeExpired = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineCrews,
          [],
          {#includeExpired: includeExpired},
        ),
        returnValue: _i3.Future<List<_i5.Crew>>.value(<_i5.Crew>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.Crew>>.value(<_i5.Crew>[]),
      ) as _i3.Future<List<_i5.Crew>>);

  @override
  _i3.Future<void> storeCrewMembersOffline(
    List<_i5.CrewMember>? members, {
    _i6.SyncPriority? priority = _i6.SyncPriority.medium,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeCrewMembersOffline,
          [members],
          {#priority: priority},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.CrewMember>> getOfflineCrewMembers(
          {bool? includeExpired = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineCrewMembers,
          [],
          {#includeExpired: includeExpired},
        ),
        returnValue: _i3.Future<List<_i5.CrewMember>>.value(<_i5.CrewMember>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.CrewMember>>.value(<_i5.CrewMember>[]),
      ) as _i3.Future<List<_i5.CrewMember>>);

  @override
  _i3.Future<void> markDataDirty(
    String? key,
    Map<String, dynamic>? changes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markDataDirty,
          [
            key,
            changes,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> performSync({bool? force = false}) => (super.noSuchMethod(
        Invocation.method(
          #performSync,
          [],
          {#force: force},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> configureSyncStrategy({
    _i6.SyncStrategy? strategy,
    bool? wifiOnly,
    bool? backgroundSync,
    int? maxDataSizeMB,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #configureSyncStrategy,
          [],
          {
            #strategy: strategy,
            #wifiOnly: wifiOnly,
            #backgroundSync: backgroundSync,
            #maxDataSizeMB: maxDataSizeMB,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getStorageStats() => (super.noSuchMethod(
        Invocation.method(
          #getStorageStats,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> clearOfflineData() => (super.noSuchMethod(
        Invocation.method(
          #clearOfflineData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i9.ConnectivityService {
  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isOffline => (super.noSuchMethod(
        Invocation.getter(#isOffline),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get wasOffline => (super.noSuchMethod(
        Invocation.getter(#wasOffline),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isConnectedToWifi => (super.noSuchMethod(
        Invocation.getter(#isConnectedToWifi),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isMobileData => (super.noSuchMethod(
        Invocation.getter(#isMobileData),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get connectionType => (super.noSuchMethod(
        Invocation.getter(#connectionType),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#connectionType),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#connectionType),
        ),
      ) as String);

  @override
  String get connectionQuality => (super.noSuchMethod(
        Invocation.getter(#connectionQuality),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#connectionQuality),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#connectionQuality),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<bool> testInternetConnection() => (super.noSuchMethod(
        Invocation.method(
          #testInternetConnection,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> refreshConnectivityState() => (super.noSuchMethod(
        Invocation.method(
          #refreshConnectivityState,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool shouldSyncData() => (super.noSuchMethod(
        Invocation.method(
          #shouldSyncData,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool shouldDownloadLargeContent() => (super.noSuchMethod(
        Invocation.method(
          #shouldDownloadLargeContent,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, dynamic> getConnectionStatus() => (super.noSuchMethod(
        Invocation.method(
          #getConnectionStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void resetOfflineFlag() => super.noSuchMethod(
        Invocation.method(
          #resetOfflineFlag,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [JobMatchingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobMatchingService extends _i1.Mock
    implements _i12.JobMatchingService {
  @override
  void startJobMatchingListener() => super.noSuchMethod(
        Invocation.method(
          #startJobMatchingListener,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopJobMatchingListener() => super.noSuchMethod(
        Invocation.method(
          #stopJobMatchingListener,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
